root = "0x27b7041ff1d215e122ecac1fe93eb4b2c7cd546aed506f88b292b6a8268c38a9"
nullifier = "0x14035edf3a5a6d7610ab7affb51021d894a01df10c1edcc2b4ef9ed49d329e21"
recipient = "0x009fe9c87ec19faaf8dfe568e1f60b792966b0de06f2cd44066ca10797001da4"
amount = 1
mint = "0x005dbd5c9906392acc27811b068fe01f8b24fc36692b219a12c145889d4f4a29"
commitment = "0x20898f8e6078412f46e9c67d57617ff384e0135df2259578d6833cdd41bf5be6"
leaf = "0x0000000000000000000000000000000000000000000000000000000000000000"
index = 159000
siblings = [
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x2098f5fb9e239eab3ceac3f27b81e481dc3124d55ffed523a839ee8446b64864",
  "0x1069673dcdb12263df301a6ff584a7ec261a44cb9dc68df067a4774460b1f1e1",
  "0x1bfe873fe4e828f2688888956b3d240dd5cf4a2a081989e099fcc277c5160bc1",
  "0x09e6dc84f50f82f2e9af2ad6ef1f765591e9ba2365b2070e0a5cded46f45ff1a",
  "0x2b94cf5e8746b3f5c9631f4c5df32907a699c58c94b2ad4d7b5cec1639183f55",
  "0x2dee93c5a666459646ea7d22cca9e1bcfed71e6951b953611d11dda32ea09d78",
  "0x078295e5a22b84e982cf601eb639597b8b0515a88cb5ac7fa8a4aabe3c87349d",
  "0x1f7ae2f38a4a56f875dc9519200eee8da1321b34cc4233bb2db2d48f42f0ee65",
  "0x0e884376d0d8fd21ecb780389e941f66e45e7acce3e228ab3e2156a614fcd747",
  "0x0335722bbc2863031b31c66de738c05a34398a11913476e7b70c68bf99de592f",
  "0x10f3c8fdc9f784eb9ae29a71b52755587f6d732b2ccf2cbf1d8cfc0bff9ba27a",
  "0x2c5d82f66c914bafb9701589ba8cfcfb6162b0a12acf88a8d0879a0471b5f85a",
  "0x2c901b3ccd3ef9e36dc8126d6a06a0f48d70d3d0bd7fe0179bbf5876f4d8e11c",
  "0x01f515fabb7c3a2d2b57ee332fb1561d8590c726884cb845dc66778c146b480d",
  "0x22f98aa9ce704152ac17354914ad73ed1167ae6596af510aa5b3649325e06c92",
  "0x2a7c7c9b6ce5880b9f6f228d72bf6a575a526f29c66ecceef8b753d38bba7323",
  "0x2b554d69c9411be5437c936781f8c8db59ee6a5fd8da33ea7fe6994eafe83544",
  "0x0f57c5571e9a4eab49e2c8cf050dae948aef6ead647392273546249d1c1ff10f",
  "0x1830ee67b5fb554ad5f63d4388800e1cfe78e310697d46e43c9ce36134f72cca",
  "0x2134e76ac5d21aab186c2be1dd8f84ee880a1e46eaf712f9d371b6df22191f3e",
  "0x19df90ec844ebc4ffeebd866f33859b0c051d8c958ee3aa88f8f8df3db91a5b1",
  "0x18cca2a66b5c0787981e69aefd84852d74af0e93ef4912b4648c05f722efe52b",
  "0x2388909415230d1b4d1304d2d54f473a628338f2efad83fadf05644549d2538d",
  "0x27171fb4a97b6cc0e9e8f543b5294de866a2af2c9c8d0b1d96e673e4529ed540",
  "0x2ff6650540f629fd5711a0bc74fc0d28dcb230b9392583e5f8d59696dde6ae21",
  "0x120c58f143d491e95902f7f5277778a2e0ad5168f6add75669932630ce611518",
  "0x1f21feb70d3f21b07bf853d5e5db03071ec495a0a565a21da2d665d279483795",
  "0x24be905fa71335e14c638cc0f66a8623a826e768068a9e968bb1a1dde18a72d2",
  "0x0f8666b62ed17491c50ceadead57d4cd597ef3821d65c328744c74e553dac26d",
  "0x0918d46bf52d98b034413f4a1a1c41594e7a7a3f6ae08cb43d1a2a230e1959ef",
  "0x1bbeb01b4c479ecde76917645e404dfa2e26f90d0afc5a65128513ad375c5ff2",
]
owner = "0x009fe9c87ec19faaf8dfe568e1f60b792966b0de06f2cd44066ca10797001da4"
blinding = "0x00c732c15e9161171ba424a3c32f03d70bd6cb2c54f0f78f7e5864d80087d0d4"
nullifier_secret = "0x00cf7d603546aacea966006a71ea9421097022268388563ac259bc5f6550cb66"
