root = "0x2f1d89b74d074b5039d96b617fe46bd5eda7c29aea67c55320a565cbf265a17e"
nullifier = "0x045bdd7a8814731f3bba92678895c5d79fac9900173d2acaa1569db0e270cf66"
recipient = "0x00ac43a4d8101137bd54b8bcda9ad8814e1ed639013ba94ffb15d0785b8fe7f6"
amount = 1
mint = "0x003f82c463e7b19424e882bd37e33d80acad7a51a77c490db2c2ce2e6137be14"
commitment = "0x2734416707c7e215209c639d675ea7439e159358b768d6f1fdb809d44b2956ad"
leaf = "0x0000000000000000000000000000000000000000000000000000000000000000"
index = 159208
siblings = [
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x2098f5fb9e239eab3ceac3f27b81e481dc3124d55ffed523a839ee8446b64864",
  "0x1069673dcdb12263df301a6ff584a7ec261a44cb9dc68df067a4774460b1f1e1",
  "0x18f43331537ee2af2e3d758d50f72106467c6eea50371dd528d57eb2b856d238",
  "0x07f9d837cb17b0d36320ffe93ba52345f1b728571a568265caac97559dbc952a",
  "0x2b94cf5e8746b3f5c9631f4c5df32907a699c58c94b2ad4d7b5cec1639183f55",
  "0x2dee93c5a666459646ea7d22cca9e1bcfed71e6951b953611d11dda32ea09d78",
  "0x13291f98a9b6b8db9255201d7e3b0094bf92e02d0c3a36d24a30f2fa63171bb1",
  "0x0e9b5954012d53b1767e03e7a98e287d7907a0743a30b18051d98527ee330840",
  "0x0e884376d0d8fd21ecb780389e941f66e45e7acce3e228ab3e2156a614fcd747",
  "0x0c8d7f2f8bbf471920115842757cadc9403e856a0cd8915b7b32c7390060e72e",
  "0x089ede6ecd4924722a517b629216ba31b043bc79698ae01883bf36cc9cf9cb44",
  "0x2c5d82f66c914bafb9701589ba8cfcfb6162b0a12acf88a8d0879a0471b5f85a",
  "0x241a74fe8e58bcab441b5985c06cf7f7e164d2ae784584a95e5bce8e475bda21",
  "0x00e1196f9fc0cfda590c54ec0f0bbd8495942ef2a195a885bbf5f9bd154f1f3f",
  "0x22f98aa9ce704152ac17354914ad73ed1167ae6596af510aa5b3649325e06c92",
  "0x2a7c7c9b6ce5880b9f6f228d72bf6a575a526f29c66ecceef8b753d38bba7323",
  "0x062b720fac39187a5421a2540576735d22660566a03f054f93c1b0419ff1d571",
  "0x0f57c5571e9a4eab49e2c8cf050dae948aef6ead647392273546249d1c1ff10f",
  "0x1830ee67b5fb554ad5f63d4388800e1cfe78e310697d46e43c9ce36134f72cca",
  "0x2134e76ac5d21aab186c2be1dd8f84ee880a1e46eaf712f9d371b6df22191f3e",
  "0x19df90ec844ebc4ffeebd866f33859b0c051d8c958ee3aa88f8f8df3db91a5b1",
  "0x18cca2a66b5c0787981e69aefd84852d74af0e93ef4912b4648c05f722efe52b",
  "0x2388909415230d1b4d1304d2d54f473a628338f2efad83fadf05644549d2538d",
  "0x27171fb4a97b6cc0e9e8f543b5294de866a2af2c9c8d0b1d96e673e4529ed540",
  "0x2ff6650540f629fd5711a0bc74fc0d28dcb230b9392583e5f8d59696dde6ae21",
  "0x120c58f143d491e95902f7f5277778a2e0ad5168f6add75669932630ce611518",
  "0x1f21feb70d3f21b07bf853d5e5db03071ec495a0a565a21da2d665d279483795",
  "0x24be905fa71335e14c638cc0f66a8623a826e768068a9e968bb1a1dde18a72d2",
  "0x0f8666b62ed17491c50ceadead57d4cd597ef3821d65c328744c74e553dac26d",
  "0x0918d46bf52d98b034413f4a1a1c41594e7a7a3f6ae08cb43d1a2a230e1959ef",
  "0x1bbeb01b4c479ecde76917645e404dfa2e26f90d0afc5a65128513ad375c5ff2",
]
owner = "0x00ac43a4d8101137bd54b8bcda9ad8814e1ed639013ba94ffb15d0785b8fe7f6"
blinding = "0x003f43d369ec6ba53d1af1e3e5b61252f68a444680bdd0572d60522a6fc6e408"
nullifier_secret = "0x002b03e90dfc0bf15f3bdf0a6c16526d6ea92b75884f2ae9969bcf2238208541"
