[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
zivo_wrap = "8fzEszHEo8DwWRFQUpiMaAnAYK2rAec6oT4pRcZ12gMp"

[programs.devnet]
zivo_wrap = "8fzEszHEo8DwWRFQUpiMaAnAYK2rAec6oT4pRcZ12gMp"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
